name: test
run-name: Running tests
on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
      - run: go test ./...